version: '3.9'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=cdxpreinbalvbw
      - POSTGRES_PASSWORD=8b794319be9f1d93f7067a2544843ef4a466b4f9e1c0461f13185d43be2f9550
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - /var/lib/postgresql/data:/var/lib/postgresql/data
volumes:
  db:
    driver: local
